### ISSUE TITLE
me.dkzwm.widget.srl.SmoothRefreshLayout is The content view is empty.

### ISSUE THREAD

**Issue by andri7** [dkzwm/SmoothRefreshLayout#34]
**I use Android Studio 3.0 stable and My Gradle :**
    compile 'com.github.dkzwm.SmoothRefreshLayout:core:1.5.0.3'
    compile 'com.github.dkzwm.SmoothRefreshLayout:ext-two-level:1.5.0.5'
    compile 'com.github.dkzwm.SmoothRefreshLayout:ext-horizontal:1.5.0.5'

**My layout :** 
<me.dkzwm.widget.srl.SmoothRefreshLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/shRefreshLayout_readNews"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    app:sr_content="@+id/recyclerView_test_qq_activity_style">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/recyclerView_readNews"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@android:color/white"
        android:overScrollMode="never" />

</me.dkzwm.widget.srl.SmoothRefreshLayout>

**However when I use the layout it appears an error message like this :**

java.lang.RuntimeException: The content view is empty. Do you forget to added it in the XML layout file or add it in code ?
	at me.dkzwm.widget.srl.SmoothRefreshLayout.ensureTargetView(SmoothRefreshLayout.java:3002)
	at me.dkzwm.widget.srl.SmoothRefreshLayout.onFinishInflate(SmoothRefreshLayout.java:733)
	at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:876)
	at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:72)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:837)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:325)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:384)
	at com.android.tools.idea.layoutlib.LayoutLibrary.createSession(LayoutLibrary.java:193)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:547)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$3(RenderTask.java:681)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Hope you quickly check this, thank you.

**Comment by dkzwm** [comment]
@andri7 Cause by you are set this code `app:sr_content="@+id/recyclerView_test_qq_activity_style"`.
You can either remove this code or change this code to "@+id/recyclerView_readNews". So Srl can find the content view.

**Comment by dkzwm** [comment]
If you set the `sr_content` attr,  You must be sure the view of this resource ID can be found in Srl.

**Comment by andri7** [comment]
solved ... sorry this is my mistake, thanks
