### ISSUE TITLE
BUG 内存溢出

### ISSUE THREAD

**Issue by jack-laowang** [dkzwm/SmoothRefreshLayout#64]
E/MessageQueue-JNI: java.lang.StackOverflowError: stack size 8MB
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onFling(SmoothRefreshLayout.java:2281)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedPreFling(SmoothRefreshLayout.java:2593)
        at android.support.v4.view.ViewParentCompat$ViewParentCompatApi21Impl.onNestedPreFling(ViewParentCompat.java:181)
        at android.support.v4.view.ViewParentCompat.onNestedPreFling(ViewParentCompat.java:515)
        at android.support.v4.view.NestedScrollingChildHelper.dispatchNestedPreFling(NestedScrollingChildHelper.java:349)
        at android.support.v7.widget.RecyclerView.dispatchNestedPreFling(RecyclerView.java:11192)
        at android.support.v7.widget.RecyclerView.fling(RecyclerView.java:2188)
        at me.dkzwm.widget.srl.utils.ScrollCompat.flingCompat(ScrollCompat.java:199)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.dispatchNestedFling(SmoothRefreshLayout.java:3895)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.tryToDispatchNestedFling(SmoothRefreshLayout.java:3902)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onFling(SmoothRefreshLayout.java:2308)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedPreFling(SmoothRefreshLayout.java:2593)
        at android.support.v4.view.ViewParentCompat$ViewParentCompatApi21Impl.onNestedPreFling(ViewParentCompat.java:181)

**Comment by dkzwm** [comment]
@MinchinWang 你好，能否提供下使用的版本，和出现的场景

**Comment by jack-laowang** [comment]
1.6.5-beta-2' RecyclerView setEmpty，加载下一页的时候

**Comment by dkzwm** [comment]
@MinchinWang 请问setEmpty是什么操作，不是很懂你的场景，能麻烦你具体说明下吗，这边好测试下最新代码有没有这个问题

**Comment by dkzwm** [comment]
@MinchinWang `1.6.5-beta-3`修复了这个问题，可以更新试下，谢谢
