### ISSUE TITLE
  java.lang.StackOverflowError: stack size 8MB

### ISSUE THREAD

**Issue by tbxyxs** [dkzwm/SmoothRefreshLayout#95]
你好，发现2个bug：（版本v1.6.6.7）
1、在列表刚好满一页的情况，不能再次加载更多，加载更多滑不动（我现在的解决办法是把分页设置相对大点，即能让item超出一页，然后就能滑动加载更多了）
2、当一页的时候，快速向上滑动（即：加载更多关闭的情况）会栈溢出，日志如下：

 Process: cn.doall.app.debug, PID: 13836
    java.lang.StackOverflowError: stack size 8MB
        at androidx.recyclerview.widget.ChildHelper.getOffset(ChildHelper.java:117)
        at androidx.recyclerview.widget.ChildHelper.getChildAt(ChildHelper.java:180)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager.getChildAt(RecyclerView.java:8668)
        at androidx.recyclerview.widget.RecyclerView$LayoutManager$2.getChildAt(RecyclerView.java:7364)
        at androidx.recyclerview.widget.ViewBoundsCheck.findOneViewWithinBoundFlags(ViewBoundsCheck.java:222)
        at androidx.recyclerview.widget.LinearLayoutManager.findOneVisibleChild(LinearLayoutManager.java:1941)
        at androidx.recyclerview.widget.LinearLayoutManager.findFirstVisibleChildClosestToStart(LinearLayoutManager.java:1717)
        at androidx.recyclerview.widget.LinearLayoutManager.computeScrollOffset(LinearLayoutManager.java:1114)
        at androidx.recyclerview.widget.LinearLayoutManager.computeVerticalScrollOffset(LinearLayoutManager.java:1085)
        at androidx.recyclerview.widget.RecyclerView.computeVerticalScrollOffset(RecyclerView.java:2058)
        at android.view.View.canScrollVertically(View.java:17469)
        at me.dkzwm.widget.srl.util.ScrollCompat.canChildScrollDown(ScrollCompat.java:70)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.isNotYetInEdgeCannotMoveFooter(SmoothRefreshLayout.java:3798)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.isNotYetInEdgeCannotMoveFooter(SmoothRefreshLayout.java:3784)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5130)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
2019-08-23 10:39:08.727 13836-13836/cn.doall.app.debug E/AndroidRuntime:     at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
2019-08-23 10:39:08.771 13836-13836/cn.doall.app.debug E/AndroidRuntime:     at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
2019-08-23 10:39:08.813 13836-13836/cn.doall.app.debug E/AndroidRuntime:     at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
2019-08-23 10:39:21.651 13836-13836/cn.doall.app.debug E/AndroidRuntime:     at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
2019-08-23 10:39:21.697 13836-13836/cn.doall.app.debug E/AndroidRuntime:     at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.computeScrollOffset(SmoothRefreshLayout.java:5132)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedScrollChanged(SmoothRefreshLayout.java:3240)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.stopNestedScroll(SmoothRefreshLayout.java:3133)
        at me.dkzwm.widget.srl.SmoothRefreshLayout$ScrollChecker.stop(SmoothRefreshLayout.java:5245)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.onNestedPreScroll(SmoothRefreshLayout.java:2916)
        at androidx.core.view.ViewParentCompat.onNestedPreScroll(ViewParentCompat.java:341)
        at androidx.core.view.NestedScrollingChildHelper.dispatchNestedPreScroll(NestedScrollingChildHelper.java:301)
        at androidx.recyclerview.widget.RecyclerView.dispatchNestedPreScroll(RecyclerView.java:11326)
        at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3151)
        at android.view.View.dispatchTouchEvent(View.java:12527)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3026)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at me.dkzwm.widget.srl.SmoothRefreshLayout.dispatchTouchEvent(SmoothRefreshLayout.java:992)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)

**Comment by dkzwm** [comment]
@tbxyxs 好的，第二个问题定位到问题了，第一个我需要写DEMO测试下，没开启`setDisableLoadMoreWhenContentNotFull`的情况下应该不会出现Footer划不动

**Comment by tbxyxs** [comment]
> @tbxyxs 好的，第二个问题定位到问题了，第一个我需要写DEMO测试下，没开启`setDisableLoadMoreWhenContentNotFull`的情况下应该不会出现Footer划不动

第1个问题你说了setDisableLoadMoreWhenContentNotFull这个问题，我去找了下，确实是我自己设置了true，我的问题，sorry，第2个问题能不能尽管发个版，对了，我也是chengdu的

**Comment by dkzwm** [comment]
这边整理下之前的修改就会发布，大概10分钟后，需要更新下文档

**Comment by dkzwm** [comment]
@tbxyxs  大熊弟，可以更新了，你试试

**Comment by tbxyxs** [comment]
@dkzwm 可以了，完美，3Q
